language: objective-c
osx_image: xcode8.2
env:
  matrix:
  - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPad 2" SCHEME="Collections iOS"
  - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)" SCHEME="Collections
    iOS"
  - DESTINATION="platform=OS X" SCHEME="Collections macOS"
  global:
    secure: S6beXXaBoXf5W2BS8scMFJv1DywCcdo/COW66iHrf7+zK7E9+kslzdVfS4SQw0fKZR9SzGxkgYtwN3c+lTdTImb8RB2bfo+4oYTusCPRDrWHrx+86HYRiogQhPj2ijbp6SuzSXs7TMWYUs+WLMtPKoW437KPiHdECgqyTbKzkiF7DnHiikQaFYNRftcX4U20QeeddpJJuK4eugyrxJnx6HAZPHXa6uXxU8JVUmNZx94Ac8Gf34Oqi9q5mXEh4fEUP2D0DSmoivuah0PT1oj0y+O0hdT5oTBmhk/qec5bBkU9VesekZXgsT0Ct8NJbY/a7uXyJFujTQ/5JE2vhmqGTUgXNEHm9ID8FUg8DfNMjmcvRcJxYIDODY56hgvCQHeBcK0bR+6S4yvRKQCWBN3TWZKGtDpWh+nYqdZRBQpb8Hp2fH+4rz0gW7g/1UXMV8tFYA2bCt/uglc7YaDmdcxh8h5znySMr/uHAjRv1ll5Kt8zGjOyR9igviZEUpKvFNo+w6E2ZRC6DXH9RFeOlcUhdWy2+cVcDzi9tsclFGfJEr0yCFbb7j25GzSVM0PP0PoZvNV+IPBbi28K4ExM3LQCmm/WmgR+hNtdPEQhRRtC8pfQ/XbyV4S9L0J3M6hrLja0hRU/FcvVORJEw8asZJBG7VR5ZB3iLYEBFPnDsfpEs5s=
before_script:
- if [ -f ./Cartfile ]; then carthage update; fi;
script: travis_retry xcodebuild test -project Collections.xcodeproj -scheme "${SCHEME}"
  -destination "${DESTINATION}" TOOLCHAINS=swift
after_success:
- bash <(curl -s https://codecov.io/bash)
- gem install jazzy
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git clone https://github.com/dn-m/dn-m.github.io
- jazzy
- cp -r docs dn-m.github.io/Collections
- cd dn-m.github.io
- git checkout -b test
- git add .
- git commit -m "Update docs"
- git push origin test
