language: objective-c
osx_image: xcode8.2
env:
  matrix:
  - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPad 2" SCHEME="Collections iOS"
  - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)" SCHEME="Collections
    iOS"
  - DESTINATION="platform=OS X" SCHEME="Collections macOS"
  global:
    secure: HzHlU2k0TOepFV+LU12XuPjFcca8LuWrIxW/xB0S432EPdW+GHC6hpvNQq7mcJC9VAikNMcQy3ExE9jjjNAlyXZ26rxOmhIe/mkB2lVaKxGpYlahArkBjJdBp7wgfen0EQHEAx4ClxfNmoPD+DuZ2WSeYT4qnwnynpGY2tcjfM01pEOYLFXGDmmKFunkn1i9Z5bb0hWxWMffBDFd5M2bikwDqC1c/yZxEmGp8fUWtood0OnoMFh7dKq4B+0R/OMWVGg+lJjbJVU4/syY8EhnSTDQmJ6ufI6iQYyBrNtxi75VRdoh6vq8sdyhQjmP4jTY149xuURbI+GSiJLgKhy5rLKkGqNxYwhgZSc0P8q/7GcUpPavTfh9CWiFd5SSvY7Uw5bLyFzUk5c2llDJb+z/uUruFJKRsdrntY9VZpYfKvy0cfaZNwBLCWH4qSxyMXXYgdRmID7fPP35S1aIZO2UnItCpmhp4JB17tr9WSViwp2tk5hv0dEhYiZWnQz84jQDhLnjT4oGUc+byQMCMQhNP6gxbx4Srw/B/Pv+776Iu1PClLmOyLpKdCoAdSpo+PVkaoKcO4LB8lwSQzmQ66y0JD3++Y8mfancalNZ2W6N/Tlj/0XW4aa6YkPMJWLXGQxORAlZySH8+YecYSGeGSAPI628hC51frRFb1JxzqdqbWk=
before_script:
- if [ -f ./Cartfile ]; then carthage update; fi;

script: travis_retry xcodebuild test -project Collections.xcodeproj -scheme "${SCHEME}"
  -destination "${DESTINATION}" TOOLCHAINS=swift
  
after_success:

- bash <(curl -s https://codecov.io/bash)
- gem install jazzy

- git clone https://github.com/dn-m/dn-m.github.io
- cd dn-m.github.io
- git checkout -b test
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git push origin test

# - jazzy
