language: objective-c
osx_image: xcode8.2
env:
  matrix:
  - DESTINATION="platform=iOS Simulator,OS=9.3,name=iPad 2" SCHEME="Collections iOS"
  - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Pro (12.9 inch)" SCHEME="Collections
    iOS"
  - DESTINATION="platform=OS X" SCHEME="Collections macOS"
  global:
    secure: nT9WUtWp4i8yC//1gzB/kiLz427woywwA7PHcgxmoczRt6HyN3w1bNPG/9zEIlAx6H1EK8HU1QmeV2V5yFNKVOfOZ7tNtKiIEL9qe2NJNAbHPJNhYSwZmzynN8oB31pgrRZtKb8f9QnETx9H3btJUGq2jTP6iLJNRK56rIVo4cz2/IwG4ijxqGCCp6+fO5FVhgoUndhoemVIuJt1wOhFsyv98fXg5pgJ5RIL9mJ7pzdreP5qJJA4b/easNhkf1OUEIfe4tBulOXXLDc9r0aBfD1oJvgZgtOex/6WkrbxlZ2SEDyMeOSfhPi9u2rNFr391uoMv4LZx3rigOvJp9O49CgJcY+z3SZ/rTe9wPWLgkpOpN/qPMjR6hpoWM6ttoZGuaJ7h47CkHgKrws1lbCPtssHmDE6RtBsBlYOQENJRtxF8HVwjlW5HHs5dTDXfigrJ1mrM3G1NVU+rATMT1W5yMdowdYy1mf5hInlvDhR6f0JROC0tLX5F8yFC1B90oiH37qevz7THiBJMZK8LPKQ3AojmMOx7VYAl0/OwuqJECYTpkfWoH7JrV5GWo4b6bgOkLjbgJ10ExK+wJbLAE19zzadsyWuiLaqwcmaJz2h5tzXazYtA6xPKuCK8D7p4XPOnSZx/3e3ro50XvB8kEbshQOjj3omyLB4yUY+jMI0/Pc=
before_script:
- if [ -f ./Cartfile ]; then carthage update; fi;
script: travis_retry xcodebuild test -project Collections.xcodeproj -scheme "${SCHEME}"
  -destination "${DESTINATION}" TOOLCHAINS=swift
after_success:
- bash <(curl -s https://codecov.io/bash)
- gem install jazzy
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git clone https://github.com/dn-m/dn-m.github.io
- jazzy
- cp -r docs dn-m.github.io/Collections
- cd dn-m.github.io
- git checkout -b test
- git add .
- git commit -m "Update docs"
- git push origin test
